GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGhhbmEiLCJpYXQiOjE3MTUwNDI1NzJ9.y53tf1t0Q76_C9-pKjZGPYviDV1eNITBYqUHREsnGUQ

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "dhana"
}
